default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: offer_review_development

test:
  <<: *default
  database: offer_review_test

production:
  <<: *default
  database: offer_review_production
  username: offer_review
  password: <%= ENV['OFFER_REVIEW_DATABASE_PASSWORD'] %>
